server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.128:3306/guli_sms
    username: root
    password: rootroot
  redis:
    host: 192.168.11.128
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  global-config:
    db-config:
      id-type: auto
