server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.11.128

  rabbitmq:
    host: 192.168.11.128
    virtual-host: /zhaojunen
    username: zhaojunen
    password: zhaojunen

jwt:
  token:
    pubKeyPath: D:\git\gmall\rsa\rsa.pub
    userKeyName: user-key # \u672A\u767B\u5F55\u8D2D\u7269\u8F66\u7684\u552F\u4E00\u6807\u8BC6
    cookieName: gmall-token
    expireTime: 7776000

alipay:
  app_id: 2016102400748057
  notify_url: http://i32z8xt9tk.52http.tech/api/order/pay/alipay/success
  return_url: http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

