server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://192.168.11.128:3306/guli_wms
    username: root
    password: rootroot
  redis:
    host: 192.168.11.128

  rabbitmq:
    host: 192.168.11.128
    virtual-host: /zhaojunen
    username: zhaojunen
    password: zhaojunen
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml